--- 
  



      - name: Create a directory if it does not exist
        ansible.builtin.file:
         path: /opt/vault/data
         state: directory
         mode: '0755'
         owner: root
         group: root  
      
      - name: Create a directory vault.d
        ansible.builtin.file:
         path: /etc/vault.d
         state: directory
         owner: root
         group: root  
         mode: '0755'


      - name: config file
        ansible.builtin.template:
           src: config.hcl.j2
           dest: /etc/vault.d/vault.hcl
           owner: root
           group: root
           mode: '0644'     

      - name: Copy systemd init file
        ansible.builtin.template:
           src: init.service.j2 
           dest: /etc/systemd/system/vault.service
           owner: vault
           group: vault
           mode: '0644'  
           

      - name: vault service
        service:
          name: vault
          state: started
          enabled: yes  


